### ISSUE TITLE
What "6 file" means in the README?

### ISSUE THREAD

**Issue by rederyang** [Theodore-PKU/MC-DDPM#4]
As the title. 
Could you please explain what "6 files test" means in the preparation stage in the README.md? How is it different from the normal one (i.e. "test")?

Thank you.

**Comment by Theodore-PKU** [comment]
In the preparation stage, we hope to get a file list that contains the desired mri data. "6 files test" means the file list only contains 6 volumes of mri data instead of all of test data as we do in "test". We extracted 6 files for testing because sampling using MCDDPM is very slow and generate results for all the test dataset will take a very very long time.

**Comment by rederyang** [comment]
I see.
Thank you!

**Comment by rederyang** [comment]
And excuse me, could you share the weights with me? I have sent a request to you on google drive.

I would appreciate it very much.

**Comment by Theodore-PKU** [comment]
I'm sorry for having forgotten to change the permission in google drive. Now the trained model should be accessible. Try this link: https://drive.google.com/drive/folders/1tgEI7GOcb2zF29dq0obYP1SMkXR38cpZ?usp=sharing

**Comment by rederyang** [comment]
Thanks! 😃
